### PR TITLE
tweaked slots API for more idiomatic syntax

### PR DESCRIPTION
**Pull request by FND**
> `makeSlots` now generates a `Slots` macro so we can use a JSX element
> instead of an expression
>
> I had also considered the following:
>
>     <Slot from={children} header />
>     <Slot from={children} unnamed />
>     <Slot from={children} footer />
>
> however, I was uncomfortable
> a) overloading `Slot` for use on both the producer and the consumer end
> b) redundantly processing `children`, which seems inevitable if each of
>    those elements is to be independent (in order to avoid having to
>    invoke `determineSlots` up front)

given:
```jsx
<Card>
    <Slot name="header">
        <h1>Hello World</h1>
    </Slot>
    <Slot name="footer">
        <footer>…</footer>
    </Slot>
    <p>lorem ipsum dolor sit amet</p>
</Card>
```

before:
```jsx
function Card(_, ...children) {
    let slots = determineSlots(children);
    return <div class="card">
        {slots.get("header")}
        {slots.unnamed}
        {slots.get("footer")}
    </div>;
}
```

after:
```jsx
function Card(_, ...children) {
    let Slots = makeSlots(children);
    return <div class="card">
        <Slots get="header" />
        <Slots unnamed />
        <pre>{Slots.names().join(", ")}</pre>
        <Slots get="footer" />
    </div>;
}
```

### CODE REVIEW

**Comment by larsrh** [comment]
What feels weird to me about this is that there's a confusion between cause and effect. In the macro, you define:

```js
    let Slots = makeSlots(children);
```

But at that point, the children _already_ contain the `<Slot>` elements.

Also, I don't understand this point:

>  a) overloading Slot for use on both the producer and the consumer end

Isn't that still the case here?

**Review by larsrh — APPROVED** [review]

**Comment by FND** [comment]
🙅‍♂ Discussion elsewhere has revealed a few issues:

*   this new API does not allow for fallback content (i.e. optional slots), which previously could be achieved with regular conditionals:

    ```jsx
    {slots.get("header") || (
        <h1>{documentTitle}</h1>
    )}
    ```

    now we'd need some sort of slot-specific approach:

    ```jsx
    <Slots get="header">
        <h1>{documentTitle}</h1>
    </Slots>
    ```

    ```jsx
    {Slots.has("header") ? (
        <Slots get="header" />
    ) : (
        <h1>{documentTitle}</h1>
    )}
    ```

    neither of which seems desirable? (note that the first option doesn't do lazy evaluation)

*   terminology is inverted when compared with [Shadow DOM slots](https://developers.google.com/web/fundamentals/web-components/shadowdom#slots):

    ```html
    #shadow-root
        <slot name="header"></slot>
        <slot></slot>
        <slot name="footer"></slot>
    ```

    ```html
    <my-card>
        <h1 slot="header">Hello World</h1>
        <div slot="footer">disclaimer</div>
        <p>lorem ipsum dolor sit amet</p>
    </my-card>
    ```

    complate has no equivalent for that universal `slot` attribute, instead we need a virtual container (akin to `<Fragment>`):

    ```jsx
    function Card(_, ...children) {
        let Slots = makeSlots(children); // transform data structure
        return <div class="card">
            <Slots get="header" />
            <Slots unnamed />
            <Slots get="footer" />
        </div>
    }
    ```

    ```jsx
    <my-card>
        <Slot name="header">
            <h1>Hello World</h1>
        </Slot>
        <Slot name="footer">disclaimer</Slot>
        <p>lorem ipsum dolor sit amet</p>
    </my-card>
    ```

    SDOM's `<slot>` corresponds to `<Slots>` (pl.) in the markup _definition_ whereas `[slot]` corresponds to `<Slot>` (sg.) on the invocation end

    SDOM's interpretation/perspective probably makes more sense, but either way finding intuitive terminology does seem important here - which raises the question: what's a suitable counterpart to "slot"?

**Review by joyheron — CHANGES_REQUESTED** [review]
I prefer the Vanilla JS approach which is in the current implementation.
This is because:

1. Macros usually return functions which create HTML elements. `<Slot>` is now an exception to this rule, which I think is ok because its function is to create a placeholder within an existing template. But using a Macro to create the `Slots` wrapper feels like we could be encouraging a programming model which we later will regret encouraging (this is more of a "Bauchgefühl", I could very well be wrong about this)
2. I think the Vanilla JS variant is much easier to use in JS expressions, which would make it more useful in general.

**Comment by joyheron** [comment]
I also prefer `findSlots` to `determineSlots` for the function name, but I'm not sure exactly why. It might be because the name is shorter.

**Comment by FND** [comment]
Yup, looks like we're in agreement; this is a nonstarter.

I was gonna change the name to `makeSlots` (also because it's more concise, which I do think is important) - but it's reminiscent of some kinda factory, which seems unhelpful. So I'll [keep pondering](https://en.wikipedia.org/wiki/Alexander_Kotov#%22Kotov_syndrome%22)...

**Comment by joyheron** [comment]
I think I like `findSlots` better than `makeSlots`, because the slots have already been created by the user. We just need to find them inside the children. Or maybe `extract` them. 

But I think it's a matter of perspective about who is "creating" them. 

Hmm... maybe `retrieveSlots` ? It's not as consise, but as a user of the Macro, I think I would mentally want to `retrieve` the slots that I had defined in my children.

I'm just thinking out loud.

**Comment by FND** [comment]
I appreciate you sharing your thought process. Allow me to do the same:

What's clumsily called `determineSlots` takes an arbitrary list of children¹ and sorts them into buckets: some named² plus unnamed remainder. It feels like there should be a name for this transformation (other than "group" or "categorize"; @larsrh could probably point to some Leibniz tome with accompanying type signature).

Because it's a straightforward and comprehensive transformation (and because nothing's ever good enough), I'm somewhat uncomfortable with all those terms we've mentioned: "make", "find", "extract", "retrieve".

Perhaps the root of the issue here is that we haven't found an evocative terminological distinction for placeholders (within the respective macro) and content (when invoking that macro).

🤔 Having said that, "resolve" might work - but that might just be Kotov speaking.

¹ arbitrarily nested, because JSX, but only root-level items are taken into account for this process

² right now, each named slot can only occur once (though it can hold an arbitrary list of children) - not sure whether there's a reasonable scenario for multiple occurrences of the same slot

**Comment by joyheron** [comment]
For me the transformation that takes place under the hood is more of an implementation detail, so my suggestions were more aimed at the developer perception of what the function does.

That being said, I probably could get behind "resolve".

I've also had a bit of difficulty with the terminology around using slots, but it might be because I haven't used them long enough. 

> ² right now, each named slot can only occur once (though it can hold an arbitrary list of children) - not sure whether there's a reasonable scenario for multiple occurrences of the same slot

Personally I can't think of a use case where this would be necessary.

**Pull request closed without merging**
